# <center> Numpy Basics </center>

In [1]:
#import numpy module with alias np

import numpy as np

We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [2]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it

arr = np.array([1,2,3])

In [3]:
# print output

arr

array([1, 2, 3])

## Dimensions in Arrays

Create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [4]:
#define a,b,c and d as instructed above

a = 10
b = [1,2,3]
c = [1,2,3],[4,5,6]
d =[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]



Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [5]:
#print dimentions of a,b, c and d

print('Dimention of a:', np.ndim(a))
print('Dimention of b:', np.ndim(b))
print('Dimention of c:', np.ndim(c))
print('Dimention of d:', np.ndim(d))



Dimention of a: 0
Dimention of b: 1
Dimention of c: 2
Dimention of d: 3


Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute



In [6]:
# print shape of each a,b ,c and d

print('Shape of a:', np.shape(a))
print('Shape of b:', np.shape(b))
print('Shape of c:', np.shape(c))
print('Shape of d:', np.shape(d))



Shape of a: ()
Shape of b: (3,)
Shape of c: (2, 3)
Shape of d: (2, 2, 3)


Lets check data type passed in our array. To check data type you can use dtype attribute

In [7]:
# print data type of c and d





Above output mean our array is having int type elements in it.

Lets check the type of our variable. To check type of any numpy variable use type() function 

In [8]:
#print type of a and b variable

print("Type of vaiable a", type(a))
print("Type of vaiable b", type(b))

Type of vaiable a <class 'int'>
Type of vaiable b <class 'list'>


In [9]:
# Lets check length of array b, using len() function

len(b)

3

Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [10]:
# Define l1,l2,l3 and l4 as stated above.

l1 = [10,20,30]
l2 = [40,50,60]

l3 = np.array(l1)
l4 = np.array(l2)



Lets multiply each elements of l1 with corresponding elements of l2

In [11]:
#code here as instructed above

result1 = [x * y for x, y in zip(l1, l2)]
result1


[400, 1000, 1800]

Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [12]:
result2 = l3 * l4
result2

array([ 400, 1000, 1800])

**NOTE - Numpy arrays are faster than lists.**

You know in many data science interviews it is asked that what is the difference between list and array.


In [13]:
#Create a numpy array using arange with 1 and 11 as parameter in it

array = np.arange(1,12)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [14]:
# Create an array using arange passing 1,11 and 2 as parameter in iter

array= np.arange(1,12,2)
array

array([ 1,  3,  5,  7,  9, 11])

In [15]:
# create numpy array using eye function with 3 as passed parameter

array = np.eye(3)
array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# Using arange() to generate numpy array x with numbers between 1 to 16
x=np.arange(1,17)
x


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [17]:
# Reshape x with 2 rows and 8 columns

x=x.reshape(2,8)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array


In [18]:
# reshaoe x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:

x=x.reshape(2,4,2)
x

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [19]:
# Use unknown dimention to reshape x into 2-D numpy array with shape 4*4

array = np.arange(1,17)
array_reshaped=array.reshape(4,4)
array_reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
# Use unknown dimention to  reshape x into 3-D numpy array with 2 arrays that contains 4 arrays
y= np.arange(1,17)
y= y.reshape(2,4,2)

y

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [21]:
# Flattening y

y_flattened = y.flatten()
y_flattened


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [22]:
# Create an array a with all even numbers between 1 to 17
a = np.arange(2,18,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [23]:
# Get third element in array a
third_element = a[2]
third_element

6

In [24]:
#Print 3rd, 5th, and 7th element in array a

third_element = a[2]
fifth_element = a[4]
seventh_element = a[6]

print("Third_element:",third_element)
print("Fifth_element:",fifth_element)
print("Seventh_element:",seventh_element)



Third_element: 6
Fifth_element: 10
Seventh_element: 14


Lets check the same for 2 D array

In [25]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
a = np.arange(1,10)
a=a.reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
# print the 3rd element from the 3rd row of a

element = a[2,2]
element

9

Well done!

Now lets check indexing for 3 D array 

In [27]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.

b = np.array([[[1, 2, 3], 
               [4, 5, 6]], 
              [[7, 8, 9], 
               [10, 11, 12]]])

b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [28]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.

element= b[1,0,2]
element

9

In [29]:
# Create 1D array

arr= np.arange(1,10)
arr



array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# Slice elements from 1st to 5th element from the following array:

arr[:5]

array([1, 2, 3, 4, 5])

Note: The result includes the start index, but excludes the end index.



In [31]:
# Slice elements from index 5 to the end of the array:

arr[5:]


array([6, 7, 8, 9])

In [32]:
# Slice elements from the beginning to index 5 (not included):

arr[:5]

array([1, 2, 3, 4, 5])

**STEP**

Use the step value to determine the step of the slicing:

In [33]:
# Print every other element from index 1 to index 7:

for i in range(1,8,2):
    print(i)


1
3
5
7


In [34]:
# Return every other element from the entire array arr:

result = arr[::2]
result


array([1, 3, 5, 7, 9])

**Array slicing in 2-D array.**

In [35]:
# Print array a

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
# From the third element, slice elements from index 1 to index 5 (not included) from array 'a'

result = [sublist[1:5] for sublist in a[2:]]
result

[array([8, 9])]

In [37]:
# In array 'a' print index 2 from all the elements :

for substing in a:
    print(substing[2])

3
6
9


In [38]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:
for sublist in a:
    print(sublist[1:])


[2 3]
[5 6]
[8 9]


Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view

In [39]:
x1= [11,12,13,14,15]

In [40]:
# assign 
x2 = x1

In [41]:
#print x1 and x2

x1, x2



([11, 12, 13, 14, 15], [11, 12, 13, 14, 15])

Ok now you have seen that both of them are same 

In [42]:
# change 1st element of x2 as 10

x2[0]=10


In [43]:
#Again print x1 and x2

x1, x2


([10, 12, 13, 14, 15], [10, 12, 13, 14, 15])

In [44]:
# Check memory share between x1 and x2

print(id(x1) == id(x2))

True


Hey It's True they both share memory

Shall we try **view()** function also likwise.

In [45]:
# Create a view of x1 and store it in x3.
x3 = x1[:]
x3


[10, 12, 13, 14, 15]

In [46]:
# Again check memory share between x1 and x3

print(id(x1)==id(x3))


False


Woh! simple assignment is similar to view. That means 
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [47]:
#Change 1st element of x3=100

x3[0]= 100

In [48]:
#print x1 and x3 to check if changes reflected in both

x1, x3


([10, 12, 13, 14, 15], [100, 12, 13, 14, 15])

Now its proved.

Lets see how **Copy()** function works

In [49]:
# Now create an array x4 which is copy of x1

x4= x1.copy()



In [50]:
# Change the last element of x4 as 900

x4[4]=900



In [51]:
# print both x1 and x4 to check if changes reflected in both

x1, x4



([10, 12, 13, 14, 15], [10, 12, 13, 14, 900])

Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

Still not convinced? Ok lets see if they both share memory or not

In [52]:
#Check memory share between x1 and x4




**hstack vs vstack function**


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function: 

1. hstack() to stack along rows.
2. vstack()  to stack along columns

In [53]:
# stack x1 and x4 along columns.

vstacks= np.vstack((x1,x4))
vstacks

array([[ 10,  12,  13,  14,  15],
       [ 10,  12,  13,  14, 900]])

In [54]:
#stack x1 and x4 along rows

hstacks= np.hstack((x1,x4))
hstacks

array([ 10,  12,  13,  14,  15,  10,  12,  13,  14, 900])

We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

In [55]:
arr1 = np.array([ 10,  12,  13,  14,  15])
arr2 = np.array([ 10,  12,  13,  14,  900])


In [56]:
##join arr1 and arr2 along rows using concatenate() function
result = np.concatenate((arr1,arr2), axis = 0)

result

array([ 10,  12,  13,  14,  15,  10,  12,  13,  14, 900])

In [57]:
##join arr1 and arr2 along columns using concatenate() function

# Reshape arrays to have a single column
arr1_column = arr1.reshape(-1, 1)
arr2_column = arr2.reshape(-1, 1)

result = np.concatenate((arr1_column, arr2_column), axis=1)
result

array([[ 10,  10],
       [ 12,  12],
       [ 13,  13],
       [ 14,  14],
       [ 15, 900]])

## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [58]:
# append arr2 to arr1

result = np.append([arr1],[arr2], axis=0)
result

array([[ 10,  12,  13,  14,  15],
       [ 10,  12,  13,  14, 900]])

Lets use insert() function which Inserts values into array before specified index value

In [59]:
# Inserts values into array x1 before index 4 with elements of x4

result_insert= np.insert(x1,4,x4)
result_insert

array([ 10,  12,  13,  14,  10,  12,  13,  14, 900,  15])

You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [60]:
# delete 2nd element from array x2

result_delete= np.delete(x2,1)
result_delete

array([10, 13, 14, 15])

Did you see? 2 value is deleted from x2 which was at index position 2